version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 15
  labels:
    - 'dependencies'
  groups:
    python-packages:
      patterns:
        - "*"