"""bobbin webhooks: provider, bobbin_id, org_id

Revision ID: d86426f71dca
Revises: 1cefaa1e870b
Create Date: 2026-06-23 17:14:39.908901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (autogenerated column types reference sqlmodel.sql.sqltypes)


# revision identifiers, used by Alembic.
revision: str = 'd86426f71dca'
down_revision: Union[str, Sequence[str], None] = '1cefaa1e870b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing rows are all TC2 endpoints: backfill provider, then drop the server_default.
    op.add_column(
        'webhookendpoint',
        sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='tutorcruncher'),
    )
    op.alter_column('webhookendpoint', 'provider', server_default=None)
    op.add_column('webhookendpoint', sa.Column('bobbin_id', sa.Integer(), nullable=True))
    # branch_id -> org_id preserves existing data (autogenerate sees this as drop + add).
    op.alter_column('webhookendpoint', 'branch_id', new_column_name='org_id', existing_type=sa.INTEGER())
    op.alter_column('webhookendpoint', 'tc_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('uq_org_bobbin', 'webhookendpoint', ['org_id', 'bobbin_id'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('uq_org_bobbin', 'webhookendpoint', type_='unique')
    op.alter_column('webhookendpoint', 'tc_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('webhookendpoint', 'org_id', new_column_name='branch_id', existing_type=sa.INTEGER())
    op.drop_column('webhookendpoint', 'bobbin_id')
    op.drop_column('webhookendpoint', 'provider')
