"""initial schema

Revision ID: 1cefaa1e870b
Revises: 
Create Date: 2026-06-23 17:02:13.897529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (autogenerated column types reference sqlmodel.sql.sqltypes)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cefaa1e870b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhookendpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tc_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('webhook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tc_id')
    )
    op.create_index(op.f('ix_webhookendpoint_timestamp'), 'webhookendpoint', ['timestamp'], unique=False)
    op.create_table('webhooklog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('webhook_endpoint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['webhook_endpoint_id'], ['webhookendpoint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooklog_timestamp'), 'webhooklog', ['timestamp'], unique=False)
    op.create_index(op.f('ix_webhooklog_webhook_endpoint_id'), 'webhooklog', ['webhook_endpoint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhooklog_webhook_endpoint_id'), table_name='webhooklog')
    op.drop_index(op.f('ix_webhooklog_timestamp'), table_name='webhooklog')
    op.drop_table('webhooklog')
    op.drop_index(op.f('ix_webhookendpoint_timestamp'), table_name='webhookendpoint')
    op.drop_table('webhookendpoint')
    # ### end Alembic commands ###
