name: CI

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: '3.11'

    - name: install dependencies
      run: |
        make install
        pip freeze
    - name: lint
      run: make lint

    - name: test
      run: |
        make reset-db
        make test

    - name: codecov
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: 'b7974c62-4f7b-4c9f-8b68-af24bc72a438'

#  deploy:
#    needs:
#      - test
#    if: "success() && startsWith(github.ref, 'refs/tags/')"
#    runs-on: ubuntu-latest
#
#    steps:
#      - run: curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}